[package]
name = "example-01-linux-basic"
version = "0.1.0"
authors = ["Alexander Korolev <alexander.korolev.germany@gmail.com>"]
edition = "2018"

[dependencies]
actix-web="3.0"
actix-web-static-files = "3"

[build-dependencies]
actix-web-static-files = "3"